name: CI

on:
  pull_request:
    branches: [staging, main]

jobs:
  test:
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: db-finza-2026
          POSTGRES_DB: finza_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "postgresql://postgres:db-finza-2026@localhost:5432/finza_test"
      DIRECT_URL: "postgresql://postgres:db-finza-2026@localhost:5432/finza_test"
      JWT_SECRET: "placeholder_secret_minimum_8"

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Instalar dependências
        run: bun install

      - name: Gerar Prisma Client
        run: bunx prisma generate
        working-directory: packages/api

      - name: Sincronizar Banco de Teste
        run: bunx prisma db push
        working-directory: packages/api

      - name: Rodar testes da API
        run: bun run test
        working-directory: packages/api